using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

namespace Graphs4Social
{
    public partial class AdicionaAmigo : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            BLL.Utilizador user = new BLL.Utilizador();

            if (User.Identity.IsAuthenticated)
            {
            string nome = User.Identity.Name;
            DataTable table = user.getUtilizadoresDisponiveis(nome);
            GridViewUsers.DataSource = table;
            GridViewUsers.ShowHeader = false;
            GridViewUsers.AutoGenerateSelectButton = true;
            GridViewUsers.AutoGenerateEditButton = true;
            GridViewUsers.AutoGenerateDeleteButton = true;
            GridViewUsers.DataBind();

            }
            else
            {
                Response.Redirect("~/Account/Login");
            }
        }
    }
}